version: '3.1'

services:
  web:
    build:
      context: ./conf
      dockerfile: Dockerfile
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./estate:/mnt/extra-addons/estate
      - ./estate_account:/mnt/extra-addons/estate_account
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    networks:
      - backend
  init:
    build:
      context: ./conf
      dockerfile: Dockerfile
    container_name: odoo17_init
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./conf/config:/etc/odoo/config
      - ./addons:/mnt/extra-addons
    networks:
      - backend
    command: 
      odoo -d odoo -u estate -i base,mail,contacts --db_host=db
      --db_user=odoo --db_password=odoo --without-demo=all --stop-after-init
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres_16
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
